### ISSUE TITLE
Support for non-ascii letters

### ISSUE THREAD

**Issue by eitland** [artynusov/MacTimeLog#10]
I mostly write english at work but often need to use norwegian/german names. The current version doesn't work with non ascii letters.

**Comment by artynusov** [comment]
It uses utf-8 encoding and should work with most non-ascii letters, what is exactly not working for you ?

**Comment by eitland** [comment]
Example: writing ÆØÅ leaves this in the log : √Ü√ò√Ö

**Comment by artynusov** [comment]
Does It display fine in the MacTimeLog window and display gibberish when you use "View->Log"  ? By default log opens with TextEdit, which is not working correctly with utf8, you can change editor in Preferences, TextMate for example works fine.

**Comment by eitland** [comment]
Thank you for your quick reply!

I'm not entirely convinced. My TextMate trial has expired but it shows up wrong not only in TextEdit, but also in Fraise (Smultron), jEdit, and XCode. 

But then, I've only been using Mac for a few months and might have missed something.

**Comment by artynusov** [comment]
You're welcome!
With Smultron try "Text -> Reload Text With Encoding -> UTF-8"

**Comment by eitland** [comment]
It worked! Thanks a lot! 

And yes,  it open with correct encoding in TextMate but uses wrong encoding everywhere(?) else.
