### ISSUE TITLE
Error while opening with an empty project

### ISSUE THREAD

**Issue by JanBurp** [artynusov/MacTimeLog#11]
It is possible to add a project with an empty name.
If you choose that project, close the program and then star again you get this error:

An unexpected error has occurred
(KeyError: None)

Pressing Continue will proceed without further problems.

Solution might be as simple as making it impossible to add empty projectnames.

**Comment by DMaiorino** [comment]
Hello,

I have made a correction to prevent black spaces from being added to project names. Made pull request to the main with name "Updated SDK and prevent blank project names."

Awaiting feedback.

**Comment by DMaiorino** [comment]
This issue has been resolved in https://github.com/SPlyer/MacTimeLog/pull/16. Should be safe to close this out.

**Comment by artynusov** [comment]
Thanks, David!
