### ISSUE TITLE
Add keyboard shortcuts for all menu options

### ISSUE THREAD

**Issue by infotexture** [artynusov/MacTimeLog#2]
- **View > Reports** (Command+R)
- **View > Log** (Command+L)

**Comment by artynusov** [comment]
Good suggestion, thanks

**Comment by infotexture** [comment]
While you're at it, it would be nice if the text entry field in the main window supported standard system shortcuts such as **Cut, Copy, Paste, Select All, Undo**.

Cut, Copy & Paste appear in the context menu, but the keyboard shortcuts don't currently work.
