### ISSUE TITLE
Report view date fields should default to current date (always show?)

### ISSUE THREAD

**Issue by infotexture** [artynusov/MacTimeLog#7]
When the **Custom** period is selected in **Reports** view, date fields should default to current date.

Currently, both fields appear with January 12, 2009, which is seldom useful. Either set both to display the current date, or something like from January 1 of the current year to the current date.

_Consider also showing date fields (read only?) when other *_Period*\* options are selected.*

**Comment by artynusov** [comment]
Good point, I actually planed to do it, but something more important popped up and I forgot about it.

**Comment by infotexture** [comment]
Please reopen this issue and consider implementing a fix for the next release.

**Comment by artynusov** [comment]
I actually fixed it, but it seems that it didn't get into release so far :)
